from app.routers import auth  # noqa: F401
from app.routers import users  # noqa: F401
from app.routers import teams  # noqa: F401
from app.routers import skills  # noqa: F401
from app.routers import plans  # noqa: F401
from app.routers import export  # noqa: F401
from app.routers import domains  # noqa: F401
from app.routers import catalog  # noqa: F401
from app.routers import certification  # noqa: F401
from app.routers import feedback  # noqa: F401
from app.routers import reporting  # noqa: F401
from app.routers import search  # noqa: F401
